let lessonIndex=0,soundOn=true,gameIndex=0,gameScore=0;
function $(id){return document.getElementById(id)}
function speak(text,lang){if(!soundOn||!window.speechSynthesis)return;window.speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(text);u.lang=lang||'en-IN';u.rate=.8;window.speechSynthesis.speak(u)}
function renderLesson(){var w=window.LITTLE_ENGLISH_LESSONS[lessonIndex%window.LITTLE_ENGLISH_LESSONS.length];$('wordEnglish').textContent=w[0];$('wordTelugu').textContent=w[1];$('wordSentence').textContent=w[2];$('wordTeluguSentence').textContent=w[3];$('wordEmoji').textContent=w[4];$('compareTe').textContent=w[1];$('compareEn').textContent=w[0]}
function showMode(name){['talk','learn','games'].forEach(function(x){$(x+'Panel').classList.toggle('hidden',x!==name)});document.querySelectorAll('.mode').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-mode')===name)});if(name==='learn')renderLesson();if(name==='games')renderGame()}
function talk(text){var c=$('conversation');var d=document.createElement('div');d.className='bubble child';d.textContent='You: '+text;var s=document.createElement('div');s.className='bubble sunny';s.textContent='Sunny: Nice! '+text;c.appendChild(d);c.appendChild(s);c.scrollTop=c.scrollHeight;speak('Nice! '+text,'en-IN')}
function mic(){if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){$('statusText').textContent='Microphone is not available. Use a quick answer.';return}navigator.mediaDevices.getUserMedia({audio:true}).then(function(stream){stream.getTracks().forEach(function(t){t.stop()});$('statusText').textContent='Microphone is ready.'}).catch(function(){$('statusText').textContent='Please allow microphone access.'})}
function renderGame(){var list=window.UKG_GAME_WORDS||[];var word=list[gameIndex%list.length];var emoji=(window.UKG_GAME_EMOJI||{})[word]||'❓';$('gameEmoji').textContent=emoji;$('gameFeedback').textContent='What is this?';$('choices').innerHTML='';var choices=[word];while(choices.length<4){var other=list[Math.floor(Math.random()*list.length)];if(choices.indexOf(other)<0)choices.push(other)}choices.sort(function(){return Math.random()-.5});choices.forEach(function(x){var b=document.createElement('button');b.type='button';b.textContent=x;b.onclick=function(){if(x===word){$('gameFeedback').textContent='Great job! ⭐';gameScore++;$('gameScore').textContent=gameScore;speak('Great job! '+x,'en-IN');setTimeout(function(){gameIndex++;renderGame()},500)}else{$('gameFeedback').textContent='Try again!';speak('Try again','en-IN')}};$('choices').appendChild(b)})}
function init(){document.querySelectorAll('.mode').forEach(function(b){b.onclick=function(){showMode(b.getAttribute('data-mode'))}});$('nextWord').onclick=function(){lessonIndex++;renderLesson()};$('playEnglish').onclick=function(){var w=window.LITTLE_ENGLISH_LESSONS[lessonIndex%window.LITTLE_ENGLISH_LESSONS.length];speak(w[2],'en-IN')};$('playTelugu').onclick=function(){var w=window.LITTLE_ENGLISH_LESSONS[lessonIndex%window.LITTLE_ENGLISH_LESSONS.length];speak(w[3],'te-IN')};$('soundToggle').onclick=function(){soundOn=!soundOn;$('soundToggle').textContent=soundOn?'🔊':'🔇'};document.querySelectorAll('[data-say]').forEach(function(b){b.onclick=function(){talk(b.getAttribute('data-say'))}});$('micButton').onclick=mic;renderLesson();renderGame()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();