window.LITTLE_ENGLISH_LESSONS=window.LITTLE_ENGLISH_LESSONS||[];
window.LITTLE_ENGLISH_LESSONS.push(
['hello','హలో','Hello, my friend.','హలో, నా స్నేహితుడా.','👋'],['hello','హలో','Hello, good morning.','హలో, శుభోదయం.','👋'],
['good morning','శుభోదయం','Good morning, mother.','శుభోదయం అమ్మ.','🌅'],['good morning','శుభోదయం','Good morning, teacher.','శుభోదయం టీచర్.','🌅'],
['good night','శుభరాత్రి','Good night, mother.','శుభరాత్రి అమ్మ.','🌙'],['good night','శుభరాత్రి','Good night, everyone.','శుభరాత్రి అందరికీ.','🌙'],
['please','దయచేసి','Please give me water.','దయచేసి నాకు నీళ్లు ఇవ్వండి.','🙏'],['please','దయచేసి','Please help me.','దయచేసి నాకు సహాయం చేయండి.','🙏'],
['thank you','ధన్యవాదాలు','Thank you, mother.','ధన్యవాదాలు అమ్మ.','❤️'],['thank you','ధన్యవాదాలు','Thank you for the gift.','బహుమతికి ధన్యవాదాలు.','❤️'],
['sorry','క్షమించండి','Sorry, I made a mistake.','క్షమించండి, నేను పొరపాటు చేశాను.','🙂'],['sorry','క్షమించండి','Sorry, I broke the toy.','క్షమించండి, నేను బొమ్మను పగలగొట్టాను.','🙂'],
['what','ఏమిటి','What is this?','ఇది ఏమిటి?','❓'],['what','ఏమిటి','What is your name?','నీ పేరు ఏమిటి?','❓'],
['where','ఎక్కడ','Where is my ball?','నా బంతి ఎక్కడ ఉంది?','📍'],['where','ఎక్కడ','Where is my book?','నా పుస్తకం ఎక్కడ ఉంది?','📍'],
['who','ఎవరు','Who is she?','ఆమె ఎవరు?','👩'],['who','ఎవరు','Who is your teacher?','నీ టీచర్ ఎవరు?','👩‍🏫'],
['how','ఎలా','How are you?','నువ్వు ఎలా ఉన్నావు?','😊'],['how','ఎలా','How do you feel?','నీకు ఎలా అనిపిస్తోంది?','😊'],
['why','ఎందుకు','Why are you crying?','నువ్వు ఎందుకు ఏడుస్తున్నావు?','❓'],['why','ఎందుకు','Why is the baby sleeping?','బేబీ ఎందుకు నిద్రపోతోంది?','❓'],
['can','చేయగల','Can I play?','నేను ఆడవచ్చా?','🎮'],['can','చేయగల','Can you help me?','నువ్వు నాకు సహాయం చేయగలవా?','🤝'],
['want','కావాలి','I want a toy.','నాకు ఒక బొమ్మ కావాలి.','🧸'],['want','కావాలి','I want some milk.','నాకు కొంచెం పాలు కావాలి.','🥛'],
['like','ఇష్టం','I like bananas.','నాకు అరటిపండ్లు ఇష్టం.','👍'],['like','ఇష్టం','I like to play.','నాకు ఆడటం ఇష్టం.','👍'],
['need','అవసరం','I need help.','నాకు సహాయం కావాలి.','🆘'],['need','అవసరం','I need a pencil.','నాకు ఒక పెన్సిల్ కావాలి.','✏️'],
['help','సహాయం','Please help me.','దయచేసి నాకు సహాయం చేయండి.','🤝'],['help','సహాయం','I can help my mother.','నేను నా అమ్మకు సహాయం చేయగలను.','🤝'],
['come','రా','Come here, please.','దయచేసి ఇక్కడికి రా.','👉'],['come','రా','Come with me.','నాతో రా.','👉'],
['go','వెళ్ళు','Go to school.','పాఠశాలకు వెళ్ళు.','🏫'],['go','వెళ్ళు','Go home with father.','నాన్నతో ఇంటికి వెళ్ళు.','🏠'],
['stop','ఆపు','Stop the car.','కారు ఆపు.','🛑'],['stop','ఆపు','Stop running here.','ఇక్కడ పరుగెత్తడం ఆపు.','🛑'],
['open','తెరువు','Open the book.','పుస్తకం తెరువు.','📖'],['open','తెరువు','Open your bag.','నీ బ్యాగ్ తెరువు.','🎒'],
['close','మూసివేయి','Close the door.','తలుపు మూసివేయి.','🚪'],['close','మూసివేయి','Close your book.','నీ పుస్తకం మూసివేయి.','📖'],
['sit','కూర్చో','Sit down, please.','దయచేసి కూర్చో.','🪑'],['sit','కూర్చో','Sit near me.','నా దగ్గర కూర్చో.','🪑'],
['stand','నిలబడు','Stand up, please.','దయచేసి నిలబడు.','🧍'],['stand','నిలబడు','Stand near the door.','తలుపు దగ్గర నిలబడు.','🧍'],
['listen','విను','Listen to me.','నా మాట విను.','👂'],['listen','విను','Listen to the story.','కథ విను.','👂'],
['look','చూడు','Look at the bird.','పక్షిని చూడు.','👀'],['look','చూడు','Look at the picture.','బొమ్మను చూడు.','👀'],
['speak','మాట్లాడు','Speak in English.','ఇంగ్లీషులో మాట్లాడు.','🗣️'],['speak','మాట్లాడు','Speak slowly, please.','దయచేసి నెమ్మదిగా మాట్లాడు.','🗣️'],
['play','ఆడటం','I want to play outside.','నాకు బయట ఆడాలని ఉంది.','⚽'],['play','ఆడటం','Let us play with the ball.','మనము బంతితో ఆడుకుందాం.','⚽'],
['clean','శుభ్రం చేయి','Clean your room.','నీ గది శుభ్రం చేయి.','🧹'],['clean','శుభ్రం చేయి','My hands are clean.','నా చేతులు శుభ్రంగా ఉన్నాయి.','✨'],
['wash','కడుగు','Wash your hands.','నీ చేతులు కడుక్కో.','🧼'],['wash','కడుగు','Wash your face.','నీ ముఖం కడుక్కో.','💦'],
['wear','ధరించు','Wear your shoes.','నీ చెప్పులు వేసుకో.','👟'],['wear','ధరించు','Wear your school uniform.','నీ స్కూల్ యూనిఫాం వేసుకో.','👕'],
['give','ఇవ్వు','Give me the ball, please.','దయచేసి నాకు బంతి ఇవ్వు.','🤲'],['give','ఇవ్వు','Give the book to mother.','పుస్తకం అమ్మకు ఇవ్వు.','📖'],
['take','తీసుకో','Take your bag.','నీ బ్యాగ్ తీసుకో.','🎒'],['take','తీసుకో','Take this pencil.','ఈ పెన్సిల్ తీసుకో.','✏️'],
['bring','తీసుకురా','Bring some water.','కొంచెం నీళ్లు తీసుకురా.','💧'],['bring','తీసుకురా','Bring your book.','నీ పుస్తకం తీసుకురా.','📖'],
['wait','వేచి ఉండు','Wait for me.','నా కోసం వేచి ఉండు.','⏳'],['wait','వేచి ఉండు','Wait here, please.','దయచేసి ఇక్కడ వేచి ఉండు.','⏳'],
['ready','సిద్ధంగా','I am ready for school.','నేను స్కూల్‌కు సిద్ధంగా ఉన్నాను.','✅'],['ready','సిద్ధంగా','I am ready to play.','నేను ఆడటానికి సిద్ధంగా ఉన్నాను.','✅'],
['love','ప్రేమ','I love my mother.','నేను నా అమ్మను ప్రేమిస్తాను.','❤️'],['love','ప్రేమ','I love my family.','నేను నా కుటుంబాన్ని ప్రేమిస్తాను.','❤️'],
['family','కుటుంబం','I love my family.','నేను నా కుటుంబాన్ని ప్రేమిస్తాను.','👨‍👩‍👦'],['family','కుటుంబం','My family is happy.','నా కుటుంబం సంతోషంగా ఉంది.','👨‍👩‍👦'],
['friend','స్నేహితుడు','This is my friend.','ఇతను నా స్నేహితుడు.','🧒'],['friend','స్నేహితుడు','I play with my friend.','నేను నా స్నేహితుడితో ఆడుతాను.','🧒'],
['today','ఈ రోజు','Today is a sunny day.','ఈ రోజు ఎండగా ఉంది.','☀️'],['today','ఈ రోజు','I am going to school today.','నేను ఈ రోజు స్కూల్‌కు వెళ్తున్నాను.','🏫'],
['tomorrow','రేపు','I will go tomorrow.','నేను రేపు వెళ్తాను.','📅'],['tomorrow','రేపు','Tomorrow is a holiday.','రేపు సెలవు.','📅'],
['morning','ఉదయం','I wake up in the morning.','నేను ఉదయం నిద్రలేస్తాను.','🌅'],['morning','ఉదయం','I drink milk in the morning.','నేను ఉదయం పాలు తాగుతాను.','🥛'],
['night','రాత్రి','I sleep at night.','నేను రాత్రి నిద్రపోతాను.','🌙'],['night','రాత్రి','The sky is dark at night.','రాత్రి ఆకాశం చీకటిగా ఉంటుంది.','🌌'],
['rain','వర్షం','It is raining today.','ఈ రోజు వర్షం పడుతోంది.','🌧️'],['rain','వర్షం','I like to watch the rain.','నాకు వర్షాన్ని చూడటం ఇష్టం.','🌧️'],
['cloud','మేఘం','The cloud is white.','మేఘం తెల్లగా ఉంది.','☁️'],['cloud','మేఘం','A cloud is in the sky.','ఆకాశంలో ఒక మేఘం ఉంది.','☁️'],
['red','ఎరుపు','The ball is red.','బంతి ఎరుపు రంగులో ఉంది.','🔴'],['blue','నీలం','The sky is blue.','ఆకాశం నీలంగా ఉంది.','🔵'],
['green','ఆకుపచ్చ','The tree is green.','చెట్టు ఆకుపచ్చగా ఉంది.','🟢'],['yellow','పసుపు','The sun is yellow.','సూర్యుడు పసుపు రంగులో ఉన్నాడు.','🟡'],
['one','ఒకటి','I have one ball.','నా దగ్గర ఒక బంతి ఉంది.','1️⃣'],['two','రెండు','I have two apples.','నా దగ్గర రెండు ఆపిల్స్ ఉన్నాయి.','2️⃣'],
['three','మూడు','I see three birds.','నేను మూడు పక్షులను చూస్తున్నాను.','3️⃣'],['four','నాలుగు','I have four books.','నా దగ్గర నాలుగు పుస్తకాలు ఉన్నాయి.','4️⃣'],
['five','ఐదు','I have five pencils.','నా దగ్గర ఐదు పెన్సిల్స్ ఉన్నాయి.','5️⃣'],['six','ఆరు','I see six stars.','నేను ఆరు నక్షత్రాలను చూస్తున్నాను.','6️⃣'],
['seven','ఏడు','I see seven flowers.','నేను ఏడు పువ్వులను చూస్తున్నాను.','7️⃣'],['eight','ఎనిమిది','I see eight birds.','నేను ఎనిమిది పక్షులను చూస్తున్నాను.','8️⃣'],
['nine','తొమ్మిది','I have nine balls.','నా దగ్గర తొమ్మిది బంతులు ఉన్నాయి.','9️⃣'],['ten','పది','I have ten fingers.','నా దగ్గర పది వేళ్లు ఉన్నాయి.','🔟']
);